### register user
POST http://localhost:3000/api/v1/Uregist
Content-Type: application/json

{
    "name": "Bronya",
    "email": "nambronya@kmail.com",
    "password": "starrail",
    "identity_type": "Paspor",
    "identity_number": "2234452",
    "address": "Belobolg, Jarilo IV"
}

### index users
GET http://localhost:3000/api/v1/users


### detail users
GET http://localhost:3000/api/v1/user/5


### new bank account to existed user
POST http://localhost:3000/api/v1/Aregist
Content-Type: application/json

{
    "users_id": "8",
    "bank_name": "Bank Tabungan IPC",
    "bank_account_number": "332211278",
    "balance": 1000000
}

### index account
GET http://localhost:3000/api/v1/accounts


### detail account
GET http://localhost:3000/api/v1/account/1


### transfering money
POST http://localhost:3000/api/v1/transfer
Content-Type: application/json

{
    "source_account_id": "6",
    "destination_account_id": "5",
    "amount": 10001
}


### index transaction
GET http://localhost:3000/api/v1/transactions


### detail transaction
GET http://localhost:3000/api/v1/transaction/5